meta_product_name: "VetRAAS"
meta_title: "VetRAAS - Especialidades Veterinárias"
meta_description: "Centro de Especialidades Veterinárias"
meta_image: "cover.png" # should exist in `app/assets/images/`
